CREATE TABLE [dbo].[virtTable102]
(
[ID] [int] NOT NULL,
[Name] [nvarchar] (100) NULL
)
GO
ALTER TABLE [dbo].[virtTable102] ADD CONSTRAINT [PK__virtTabl__3214EC2716FB64C2] PRIMARY KEY CLUSTERED ([ID])
GO
