CREATE TABLE [dbo].[virtTable103]
(
[ID] [int] NOT NULL,
[Name] [nvarchar] (100) NULL
)
GO
ALTER TABLE [dbo].[virtTable103] ADD CONSTRAINT [PK__virtTabl__3214EC27EE3C6BB2] PRIMARY KEY CLUSTERED ([ID])
GO
