CREATE TABLE [dbo].[virtTable105]
(
[ID] [int] NOT NULL,
[Name] [nvarchar] (100) NULL
)
GO
ALTER TABLE [dbo].[virtTable105] ADD CONSTRAINT [PK__virtTabl__3214EC2753D6A94C] PRIMARY KEY CLUSTERED ([ID])
GO
