CREATE TABLE [dbo].[virtTable110]
(
[ID] [int] NOT NULL,
[Name] [nvarchar] (100) NULL
)
GO
ALTER TABLE [dbo].[virtTable110] ADD CONSTRAINT [PK__virtTabl__3214EC27BFF56265] PRIMARY KEY CLUSTERED ([ID])
GO
