flywayDesktop = { }

[environments.development]
url = "jdbc:sqlserver://localhost:1433;authentication=sqlPassword;databaseName=thing;encrypt=true;trustServerCertificate=true"
user = "sa"
password = "abc123!!"
displayName = "Development"

[redgateCompare]
filterFile = "filter.rgf"
